export const FETCHPOSTSBYID_PENDING = 'FETCHPOSTBYID_PENDING';
export const FETCHPOSTSBYID_SUCCESS = 'FETCHPOSTBYID_SUCCESS';
export const FETCHPOSTSBYID_FAILD = 'FETCHPOSTBYID_FAILD';

export const FETCHUSERS_PENDING = 'FETCHUSERS_PENDING';
export const FETCHUSERS_SUCCESS = 'FETCHUSERS_SUCCESS';
export const FETCHUSERS_FAILD = 'FETCHUSERS_FAILD';



